# Generated by Django 5.1.4 on 2025-01-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piercing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No definido', max_length=30)),
                ('description', models.CharField(default='Sin descripcion definida', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('photo', models.ImageField(blank='', default='', upload_to='photos/')),
            ],
            options={
                'verbose_name': 'Piercing',
                'verbose_name_plural': 'Piercings',
            },
        ),
    ]
